before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database tomato_time_2_test;' -U postgres


language: ruby

rvm:
  - 2.4.1

cache: bundler

script:
  - bundle exec rake
  - bundle exec rake send_digest

services:
  - redis-server
  - postgresql

# deploy:
#   provider: heroku
#   api_key:
#   app: blooming-reef-34254
